# Combining and Merging Data Sets.
1. ***pandas.merge*** connects rows similar to DataBase SQL joins, using keys.
2. ***pandas.concat*** glues or stacks together objects along axis.
3. ***combine_first*** instance method is used to fill in missing values in one object with values from another.

## Database-style DataFrame Mergers.
Merge or join operations combine data sets by linking rows using one or more keys.

In [39]:
from pandas import DataFrame, Series
import pandas as pd
import numpy as np

### One-to-many merge

In [40]:
students = DataFrame ({'student_id': [1, 2, 3, 4],
                      'first_name': ['Mary', 'John', 'Praveen', 'Pat']},
                     columns = ['student_id', 'first_name'])

In [41]:
student_phonebook_data = {'student_id': [1, 1, 2, 2, 3, 3, 1000],
    'phone_type': ['home', 'cell', 'cell', 'work', 'home', 'work', 'cell'],
    'phone_number': ['(212)111-2222', '(917)222-3333', '(646)333-4444', '(646)444-3333', '(718)222-5555', '(646)666-7777', '(646)000-1000']}

student_phonebook = DataFrame(student_phonebook_data, 
    columns=['student_id', 'phone_number', 'phone_type'])

In [42]:
print(students)
print() 
print(student_phonebook)

   student_id first_name
0           1       Mary
1           2       John
2           3    Praveen
3           4        Pat

   student_id   phone_number phone_type
0           1  (212)111-2222       home
1           1  (917)222-3333       cell
2           2  (646)333-4444       cell
3           2  (646)444-3333       work
4           3  (718)222-5555       home
5           3  (646)666-7777       work
6        1000  (646)000-1000       cell


#### If not specified, <i>merge</i> uses the overlapping column names as the keys.

In [43]:
pd.merge(students, student_phonebook)

student_id first_name   phone_number phone_type
0           1       Mary  (212)111-2222       home
1           1       Mary  (917)222-3333       cell
2           2       John  (646)333-4444       cell
3           2       John  (646)444-3333       work
4           3    Praveen  (718)222-5555       home
5           3    Praveen  (646)666-7777       work

#### Key is specified explicitely
Same merge, easier to read.

In [44]:
pd.merge(students, student_phonebook, on='student_id')

student_id first_name   phone_number phone_type
0           1       Mary  (212)111-2222       home
1           1       Mary  (917)222-3333       cell
2           2       John  (646)333-4444       cell
3           2       John  (646)444-3333       work
4           3    Praveen  (718)222-5555       home
5           3    Praveen  (646)666-7777       work

#### Merging DataFrames when the key column names do not match
<i>students</i> DataFrame will have a column named 'id', rather than 'student_id'.  <i>student_phonebook</i> will remain the same.

In [45]:
students2 = DataFrame ({'id': [1, 2, 3, 4],
                      'first_name': ['Mary', 'John', 'Praveen', 'Pat']},
                     columns = ['id', 'first_name'])

In [46]:
student_phonebook_data2 = {'student_id': [1, 1, 2, 2, 3, 3, 1000],
    'phone_type': ['home', 'cell', 'cell', 'work', 'home', 'work', 'cell'],
    'phone_number': ['(212)111-2222', '(917)222-3333', '(646)333-4444', '(646)444-3333', '(718)222-5555', '(646)666-7777', '(646)000-1000']}


student_phonebook2 = DataFrame(student_phonebook_data2, 
    columns=['student_id', 'phone_number', 'phone_type'])

In [47]:
print(students2)
print()
print(student_phonebook2)

   id first_name
0   1       Mary
1   2       John
2   3    Praveen
3   4        Pat

   student_id   phone_number phone_type
0           1  (212)111-2222       home
1           1  (917)222-3333       cell
2           2  (646)333-4444       cell
3           2  (646)444-3333       work
4           3  (718)222-5555       home
5           3  (646)666-7777       work
6        1000  (646)000-1000       cell


In [48]:
pd.merge(students2, student_phonebook2, left_on='id', right_on='student_id')

id first_name  student_id   phone_number phone_type
0   1       Mary           1  (212)111-2222       home
1   1       Mary           1  (917)222-3333       cell
2   2       John           2  (646)333-4444       cell
3   2       John           2  (646)444-3333       work
4   3    Praveen           3  (718)222-5555       home
5   3    Praveen           3  (646)666-7777       work

### Left, right and outer joins.

### Left join

In [49]:
pd.merge(students, student_phonebook, how='left')

student_id first_name   phone_number phone_type
0           1       Mary  (212)111-2222       home
1           1       Mary  (917)222-3333       cell
2           2       John  (646)333-4444       cell
3           2       John  (646)444-3333       work
4           3    Praveen  (718)222-5555       home
5           3    Praveen  (646)666-7777       work
6           4        Pat            NaN        NaN

### Right join

In [50]:
pd.merge(students, student_phonebook, how='right')

student_id first_name   phone_number phone_type
0           1       Mary  (212)111-2222       home
1           1       Mary  (917)222-3333       cell
2           2       John  (646)333-4444       cell
3           2       John  (646)444-3333       work
4           3    Praveen  (718)222-5555       home
5           3    Praveen  (646)666-7777       work
6        1000        NaN  (646)000-1000       cell

### Outer join

In [51]:
pd.merge(students, student_phonebook, how='outer')

student_id first_name   phone_number phone_type
0           1       Mary  (212)111-2222       home
1           1       Mary  (917)222-3333       cell
2           2       John  (646)333-4444       cell
3           2       John  (646)444-3333       work
4           3    Praveen  (718)222-5555       home
5           3    Praveen  (646)666-7777       work
6           4        Pat            NaN        NaN
7        1000        NaN  (646)000-1000       cell

### Merge on multiple keys

In [52]:
grades = DataFrame ({'student_id': [1, 2, 3],
                      'course_id': [100, 100, 100],
                    'grade': ['A', 'B', 'C']})

In [53]:
registrations = DataFrame ({'student_id': [1, 2, 3],
                       'course_id': [100, 100, 100],
                       'section': ['MW', 'MW', 'MW']})

In [54]:
grades

student_id  course_id grade
0           1        100     A
1           2        100     B
2           3        100     C

In [55]:
registrations

student_id  course_id section
0           1        100      MW
1           2        100      MW
2           3        100      MW

In [56]:
# 'on' parameter is a list of column names
pd.merge(grades, registrations, on=['student_id', 'course_id'], how='outer')

student_id  course_id grade section
0           1        100     A      MW
1           2        100     B      MW
2           3        100     C      MW

### Overlapping column names
What if both DataFrames have a column <i>first_name</i>:

In [57]:
# first name is the name of a student
students = DataFrame ({'student_id': [1, 2, 3],
                      'first_name': ['Mary', 'John', 'Praveen']},
    columns=['student_id', 'first_name'])

In [58]:
# first name is the name of an emmergency contact
emergency_contacts = DataFrame (
    {'student_id': [1, 2, 3], 
     'first_name': ['Nick', 'Laura', 'Eugene']},
    columns=['student_id', 'first_name'])

In [59]:
students

student_id first_name
0           1       Mary
1           2       John
2           3    Praveen

In [60]:
emergency_contacts

student_id first_name
0           1       Nick
1           2      Laura
2           3     Eugene

Might be difficult to read by default:

In [61]:
pd.merge(students, emergency_contacts, on='student_id')

student_id first_name_x first_name_y
0           1         Mary         Nick
1           2         John        Laura
2           3      Praveen       Eugene

Using suffixes parameter to create new column names for overlapping columns:

In [62]:
pd.merge(students, emergency_contacts, on='student_id', 
         suffixes=('_student', '_emergency_contact'))

student_id first_name_student first_name_emergency_contact
0           1               Mary                         Nick
1           2               John                        Laura
2           3            Praveen                       Eugene

### Merging on Index
You can pass <i>left_index=True</i> or <i>right_index=True</i> to merge on index.

In [63]:
left1 = DataFrame({'key':['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': range(6)})

In [64]:
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [65]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [66]:
right1

group_val
a        3.5
b        7.0

In [67]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

Note how 'c' does not appear in merge results (inner join). <br/>
See the textbook for hierarchically-indexed data merge and <i>join()</i> method.

## Concatenating Along an Axis
### Concatenate NumPy arrays
axis 0 is the rows.<br/>
axis 1 is the columns.

In [68]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
np.concatenate([arr, arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

## The <i>concat()</i> function in pandas
The following three Series objects have no index overlap.

In [71]:
s1 = Series([0, 1], index=['Apple', 'Banana'])
s1

Apple     0
Banana    1
dtype: int64

In [72]:
s2 = Series([20, 30, 40], index=['Blueberry', 'Cranberry', 'Pear'])
s2

Blueberry    20
Cranberry    30
Pear         40
dtype: int64

In [73]:
s3 = Series([500, 600], index=['Raspberry', 'Strawberry'])
s3

Raspberry     500
Strawberry    600
dtype: int64

### *concat()* glues together the values and indexes
By default, <i>concat()</i> works along axis=0, producing another Series. <br/>
Calling <i>concat()</i> glues together values and indexes.

In [74]:
pd.concat([s1, s2, s3])

Apple           0
Banana          1
Blueberry      20
Cranberry      30
Pear           40
Raspberry     500
Strawberry    600
dtype: int64

In [75]:
s1.name = 'hi'
s2.name = 'hi2'
pd.merge(s1, s2, how='outer', left_index=True, right_index=True)


hi   hi2
Apple      0.0   NaN
Banana     1.0   NaN
Blueberry  NaN  20.0
Cranberry  NaN  30.0
Pear       NaN  40.0

### If you pass axis=1, the result will be a DataFrame.
Axis 1 is the columns.

In [76]:
pd.concat([s1, s2, s3], axis=1, sort=False)

hi   hi2      0
Apple       0.0   NaN    NaN
Banana      1.0   NaN    NaN
Blueberry   NaN  20.0    NaN
Cranberry   NaN  30.0    NaN
Pear        NaN  40.0    NaN
Raspberry   NaN   NaN  500.0
Strawberry  NaN   NaN  600.0

See the textbook for more examples.

## Combining Data with Overlap.
### Combining NumPy array data.

In [77]:
a = Series([np.nan, 3.5, 4.5, np.nan], index=['d', 'c', 'b', 'a'])
a

d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [78]:
b = Series(np.arange(len(a), dtype=np.float64), index=['f', 'e', 'd', 'c'])
b[-1] = np.nan
b

f    0.0
e    1.0
d    2.0
c    NaN
dtype: float64

### Series <i>combine_first()</i> method performs the equivalent of this operation plus data alignment.

In [79]:
b.combine_first(a)

a    NaN
b    4.5
c    3.5
d    2.0
e    1.0
f    0.0
dtype: float64

### combine_first() for pandas
With DataFrames, combine_first() does the same thing column by column, so you can think of it as "patching" missing data in the calling object with the data from the object you pass:

In [80]:
df1 = DataFrame({'New York': [20, np.nan, 50, np.nan],
                'Tokyo': [np.nan, 30, np.nan, 40],
                'Paris': range(2, 18, 4)})

In [81]:
df2 = DataFrame({'New York': [1, 7, np.nan, 1, 2],
                'Tokyo': [np.nan, 3, 4, 6, 8]})

In [82]:
df1

New York  Tokyo  Paris
0      20.0    NaN      2
1       NaN   30.0      6
2      50.0    NaN     10
3       NaN   40.0     14

In [83]:
df2

New York  Tokyo
0       1.0    NaN
1       7.0    3.0
2       NaN    4.0
3       1.0    6.0
4       2.0    8.0

In [84]:
df1.combine_first(df2)

New York  Paris  Tokyo
0      20.0    2.0    NaN
1       7.0    6.0   30.0
2      50.0   10.0    4.0
3       1.0   14.0   40.0
4       2.0    NaN    8.0

In [85]:
df2.combine_first(df1)

New York  Paris  Tokyo
0       1.0    2.0    NaN
1       7.0    6.0    3.0
2      50.0   10.0    4.0
3       1.0   14.0    6.0
4       2.0    NaN    8.0